apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llmops-ingress
spec:
  rules:
    - host: llmops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llmops-service
                port:
                  number: 80
